name: go-web-app-CI/CD

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'helm/**'
      - 'k8s/**'
      - 'README.md'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Go 1.21
      uses: actions/setup-go@v5
      with:
        go-version: 1.22

    - name: Download dependencies
      run: go mod download    

    - name: Build
      run: go build -o go-web-app

    - name: Test
      run: go test ./...

  code-quality:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v6
      with:
        version: v1.60.3

  push:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GIT_TOKEN }}

    - name: Ensure VERSION file exists
      run: |
        if [ ! -f VERSION ]; then
          echo "1.0.0" > VERSION
        fi

    - name: Increment version
      id: version
      run: |
        CURRENT_VERSION=$(cat VERSION)
        echo "Current version: $CURRENT_VERSION"
        IFS='.' read -r MAJOR MINOR PATCH <<< "$CURRENT_VERSION"
        PATCH=$((PATCH + 1))
        NEW_VERSION="$MAJOR.$MINOR.$PATCH"
        echo "New version: $NEW_VERSION"
        echo $NEW_VERSION > VERSION
        echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV

    - name: Commit new VERSION
      run: |
        git config --global user.email "victoronwuka7@gmail.com"
        git config --global user.name "Chimuanya vic"
        git add VERSION
        git commit -m "Bump version to ${{ env.NEW_VERSION }}" || echo "No changes to commit"
        git push

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/go-web-app:${{ env.NEW_VERSION }}

  update-helm:
    runs-on: ubuntu-latest
    needs: push
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GIT_TOKEN }}

    - name: Update tag in Helm chart
      run: |
        sed -i "s/tag: .*/tag: \"${{ env.NEW_VERSION }}\"/" helm/go-web-app-chart/values.yaml

    - name: Commit Helm chart
      run: |
        git config --global user.email "victoronwuka7@gmail.com"
        git config --global user.name "Chimuanya vic"
        git add helm/go-web-app-chart/values.yaml
        git commit -m "Update Helm chart to ${{ env.NEW_VERSION }}" || echo "No changes to commit"
        git push