name: go-web-app-CI/CD

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
    paths-ignore:
      - 'helm/**'
      - 'k8s/**'
      - 'README.md'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go 1.21
        uses: actions/setup-go@v5
        with:
          go-version: 1.21.13

      - name: Download dependencies
        run: go mod download    

      - name: Build
        run: go build -o go-web-app

      - name: Test
        run: go test ./...

  code-quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.60.3

  set-image-tag:
    runs-on: ubuntu-latest
    outputs:
      IMAGE_TAG: ${{ steps.set_tag.outputs.IMAGE_TAG }}
    steps:
      - name: Set image tag
        id: set_tag
        run: |
          if [[ "${GITHUB_REF_TYPE}" == "tag" ]]; then
            echo "IMAGE_TAG=${GITHUB_REF_NAME}" >> $GITHUB_ENV
            echo "IMAGE_TAG=${GITHUB_REF_NAME}" >> $GITHUB_OUTPUT
          else
            echo "IMAGE_TAG=dev-${GITHUB_RUN_ID}" >> $GITHUB_ENV
            echo "IMAGE_TAG=dev-${GITHUB_RUN_ID}" >> $GITHUB_OUTPUT
          fi

  push:
    runs-on: ubuntu-latest
    needs: [build, set-image-tag]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/go-web-app:${{ env.IMAGE_TAG }}

  update-helm-chart:
    runs-on: ubuntu-latest
    needs: push
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GIT_TOKEN }}

      - name: Update image tag in Helm chart
        run: |
          sed -i 's/tag: .*/tag: "${IMAGE_TAG}"/' helm/go-web-app-chart/values.yaml

      - name: Commit and push changes
        run: |
          git config --global user.email "your-email@example.com"
          git config --global user.name "Your Name"
          git add helm/go-web-app-chart/values.yaml
          git commit -m "Update Helm chart with image tag ${IMAGE_TAG}" || echo "No changes to commit"
          git push